=== xarvh/everborn/NOTES/spells/realm.dtd
<!ELEMENT realm (name, info, book+)>
    <!ELEMENT id (#CDATA)>
    <!ELEMENT name (#CDATA)>
    <!ELEMENT info (#CDATA)>
    <!ELEMENT book (name, history, spell+)>
	<!ELEMENT history (#CDATA)>
	<!ELEMENT spell (
	    type,name,info,
	    gfx?,unit?,targA?,targS?,
	    rank,upkeep?,know,cost,bcost?,
	    code )>
	    <!ELEMENT type (#CDATA)>
	    <!ELEMENT gfx (#CDATA)>
	    <!ELEMENT unit EMPTY>
	    <!ELEMENT targA (#CDATA)>
	    <!ELEMENT targS (#CDATA)>
	    <!ELEMENT rank (#CDATA)>
	    <!ELEMENT upkeep (#CDATA)>
	    <!ELEMENT know (#CDATA)>
	    <!ELEMENT cost (#CDATA)>
	    <!ELEMENT bcost (#CDATA)>
	    <!ELEMENT code(#CDATA)>

=== xarvh/everborn/NOTES/spells/life.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/css" href="realm.css"?>
<!DOCTYPE realm SYSTEM "realm.dtd">

<realm>
    <name>Life</name>
    <info>
    The Realm of Life blah blah blah.
    </info>

    <book>
	<name>Triumphum astrorum</name>
	<history>
	Taken from blah blah blah...
	</history>

	<spell>
	    <name>Archangel</name>
	    <rank>rare</rank>
	    <type>summon</type>
	    <info>Summon a blah blah blah</info>
	    <gfx></gfx>
	    <upkeep>	 20	</upkeep>
	    <know>	100	</know>
	    <bcost>	 50	</bcost>
	    <cost>	250	</cost>
	    <unit>archangel.xml</unit>
	    <targA></targA>
	    <targS></targS>
	    <obj></obj>
	    <code>summon.cpp</code>
	</spell>

	<spell>
	    <name>Ascention</name>
	    <rank>uncommon</rank>
	    <type>unit</type>
	    <info>Endows a loyal blah blah blah blah</info>
	    <gfx></gfx>
	    <upkeep>	 20	</upkeep>
	    <know>	100	</know>
	    <cost>	250	</cost>
	    <targA>ALLIANCE_FRIENDLY</targA>
	    <targS>STATUS_ALIVE</targS>
	    <obj>ASCENTION</obj>
	    <code>unit_ench.cpp</code>
	</spell>

	
	<spell>
		<name>Charm Of Life</name>
		<rank>rare</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>  10</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost>1250</cost>
	</spell>
	
	<spell>
		<name>Crusade</name>
		<rank>rare</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>  10</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost>1100</cost>
	</spell>
	
	<spell>
		<name>Incarnation</name>
		<rank>rare</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>  12</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 500</cost>
	</spell>
	
	<spell>
		<name>Invulnerability</name>
		<rank>rare</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   5</upkeep>
		<know>   0</know>
		<bcost>  40</bcost>
		<cost> 200</cost>
	</spell>

	<spell>
		<name>Consecration</name>
		<rank>uncommon</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   8</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 400</cost>
	</spell>

	<spell>
		<name>High Prayar</name>
		<rank>uncommon</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   0</upkeep>
		<know>   0</know>
		<bcost>  60</bcost>
		<cost>   0</cost>
	</spell>
	
	<spell>
		<name>Holy Word</name>
		<rank>uncommon</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   0</upkeep>
		<know>   0</know>
		<bcost>  60</bcost>
		<cost>   0</cost>
	</spell>
	
	<spell>
		<name>Inspiration</name>
		<rank>uncommon</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   0</upkeep>
		<know>   0</know>
		<bcost>  60</bcost>
		<cost>   0</cost>
	</spell>
	
	<spell>
		<name>Life Force</name>
		<rank>uncommon</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>  10</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost>1000</cost>
	</spell>
	
	<spell>
		<name>Lionheart</name>
		<rank>uncommon</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>  20</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 950</cost>
	</spell>
	
	<spell>
		<name>Mass Healing</name>
		<rank>uncommon</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   0</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost>  50</cost>
	</spell>
	
	<spell>
		<name>Planar Seal</name>
		<rank>uncommon</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   5</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 500</cost>
	</spell>
	
	<spell>
		<name>Stream Of Life</name>
		<rank>uncommon</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   8</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 300</cost>
	</spell>
	
	<spell>
		<name>Tranquillity</name>
		<rank>uncommon</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>  10</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost>1000</cost>
	</spell>
	
	<spell>
		<name>Altar Of Battle</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   5</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 300</cost>
	</spell>
	
	<spell>
		<name>Angel</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>  15</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 550</cost>
	</spell>
	
	<spell>
		<name>Astral Gate</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   5</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 350</cost>
	</spell>
	
	<spell>
		<name>Bless</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   1</upkeep>
		<know>   0</know>
		<bcost>   8</bcost>
		<cost>  40</cost>
	</spell>
	
	<spell>
		<name>Dispel Evil</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   0</upkeep>
		<know>   0</know>
		<bcost>  25</bcost>
		<cost>   0</cost>
	</spell>
	
	<spell>
		<name>Endurance</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   1</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost>  30</cost>
	</spell>
	
	<spell>
		<name>Guardian Spirit</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   1</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost>  80</cost>
	</spell>
	
	<spell>
		<name>Holy Arms</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>  10</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 900</cost>
	</spell>
	
	<spell>
		<name>Holy Armor</name>
		<rank>uncommon</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   2</upkeep>
		<know>   0</know>
		<bcost>  18</bcost>
		<cost>  90</cost>
	</spell>
	
	<spell>
		<name>Holy Fire</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   0</upkeep>
		<know>   0</know>
		<bcost>  40</bcost>
		<cost>   0</cost>
	</spell>
	
	<spell>
		<name>Holy Weapon</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   1</upkeep>
		<know>   0</know>
		<bcost>  10</bcost>
		<cost>  50</cost>
	</spell>
	
	<spell>
		<name>Healing</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   0</upkeep>
		<know>   0</know>
		<bcost>  15</bcost>
		<cost>   0</cost>
	</spell>
	
	<spell>
		<name>Heavenly Light</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   1</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 100</cost>
	</spell>
	
	<spell>
		<name>Heroism</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   2</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 150</cost>
	</spell>
	
	<spell>
		<name>Just Cause</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   3</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 150</cost>
	</spell>
	
	<spell>
		<name>Plane Shift</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   0</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 125</cost>
	</spell>
	
	<spell>
		<name>Planar Travel</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   5</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 300</cost>
	</spell>
	
	<spell>
		<name>Prayer</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   0</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost>  30</cost>
	</spell>
	
	<spell>
		<name>Prosperity</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   2</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 250</cost>
	</spell>
	
	<spell>
		<name>Raise Fallen</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   0</upkeep>
		<know>   0</know>
		<bcost>  35</bcost>
		<cost>   0</cost>
	</spell>
	
	<spell>
		<name>Resurrection</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   0</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost> 250</cost>
	</spell>
	
	<spell>
		<name>Righteousness</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   2</upkeep>
		<know>   0</know>
		<bcost>  40</bcost>
		<cost> 200</cost>
	</spell>
	
	<spell>
		<name>True Light</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   0</upkeep>
		<know>   0</know>
		<bcost>  20</bcost>
		<cost>   0</cost>
	</spell>
	
	<spell>
		<name>True Sight</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   0</upkeep>
		<know>   0</know>
		<bcost>  20</bcost>
		<cost>   0</cost>
	</spell>
	
	<spell>
		<name>Summon Engineers</name>
		<rank>common</rank>
		<type> </type>
		<info> </info>
		<gfx> </gfx>
		<upkeep>   0</upkeep>
		<know>   0</know>
		<bcost>   0</bcost>
		<cost>   0</cost>
	</spell>
</book>
</realm>

=== xarvh/everborn/NOTES/spells/chaos.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/css" href="realm.css"?>
<!DOCTYPE realm SYSTEM "realm.dtd">

<realm>
    <name>Chaos</name>
    <info>
    Chaos reshapes.
    Animates dead matter, burns it again to ashes.
    </info>
	
    <book>
	<name>Laus Eversionis</name>
	<history>
	The Ode to Destruction is one of the most ancient....
	</history>

	<spell>
	    <name>Armageddon</name>
	    <rank>rare</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>  40</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost>1250</cost>
	</spell>

	<spell>
	    <name>Call The Void</name>
	    <rank>rare</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 500</cost>
	</spell>

	<spell>
	    <name>Chaos Surge</name>
	    <rank>rare</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>  40</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost>1000</cost>
	</spell>

	<spell>
	    <name>Great Drake</name>
	    <rank>rare</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>  30</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 900</cost>
	</spell>

	<spell>
	    <name>Burn</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  60</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Call Chaos</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  75</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Chaos Gates</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>  15</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost>1100</cost>
	</spell>

	<spell>
	    <name>Doom Bolt</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  60</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Disintegrate</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  50</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Fire Storm</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 250</cost>
	</spell>

	<spell>
	    <name>Flame Strike</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  60</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Great Wasting</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  20</bcost>
	    <cost>1000</cost>
	</spell>

	<spell>
	    <name>Hidra</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>  14</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 650</cost>
	</spell>

	<spell>
	    <name>Metor Storm</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>  10</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 900</cost>
	</spell>

	<spell>
	    <name>Raise Volcano</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 200</cost>
	</spell>

	<spell>
	    <name>Warp Lightning</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  35</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Beholder</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>  12</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 500</cost>
	</spell>

	<spell>
	    <name>Chaos Channels</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost>  50</cost>
	</spell>

	<spell>
	    <name>Chaos Rift</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>  10</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 300</cost>
	</spell>

	<spell>
	    <name>Cimeras</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>  10</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 350</cost>
	</spell>

	<spell>
	    <name>Corruption</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost>  40</cost>
	</spell>

	<spell>
	    <name>Distrupt</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  15</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Doom Bat</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   8</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 300</cost>
	</spell>

	<spell>
	    <name>Efreet</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>  15</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 550</cost>
	</spell>

	<spell>
	    <name>Eldritch Weapon</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   1</upkeep>
	    <know>   0</know>
	    <bcost>  15</bcost>
	    <cost>  75</cost>
	</spell>

	<spell>
	    <name>Flame Blade</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   2</upkeep>
	    <know>   0</know>
	    <bcost>  25</bcost>
	    <cost> 125</cost>
	</spell>

	<spell>
	    <name>Fire Ball</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  15</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Fire Bolt</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>   5</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Fire Elemental</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  20</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Fire Giant</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   3</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 150</cost>
	</spell>

	<spell>
	    <name>Hell Hounds</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   1</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost>  40</cost>
	</spell>

	<spell>
	    <name>Immolation</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   2</upkeep>
	    <know>   0</know>
	    <bcost>  30</bcost>
	    <cost> 150</cost>
	</spell>

	<spell>
	    <name>Lighting Bolt</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  10</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Magic Vortex</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  50</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Metal Fires</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   1</upkeep>
	    <know>   0</know>
	    <bcost>  30</bcost>
	    <cost> 100</cost>
	</spell>

	<spell>
	    <name>Shatter</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  12</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Wall Of Fire</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   1</upkeep>
	    <know>   0</know>
	    <bcost>  30</bcost>
	    <cost> 100</cost>
	</spell>

	<spell>
	    <name>Warp Creature</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  18</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Warp Reality</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  50</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Warp Wood</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  10</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Berserk</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  30</bcost>
	    <cost>   0</cost>
	</spell>
</book>
</realm>

=== xarvh/everborn/NOTES/spells/arcane.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<?xml-stylesheet type="text/css" href="realm.css"?>
<!DOCTYPE realm SYSTEM "realm.dtd">

<realm>
    <name>Arcane</name>
    <info>
    Arcane spells are....
    </info>
	
    <book>
	<name>ABC of Magic</name>
	<history>
	Fallen somehow from the sky straight on your head.
	</history>

	<spell>
	    <name>Awareness</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   3</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 500</cost>
	</spell>

	<spell>
	    <name>Create Artifact</name>
	    <rank>rare</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Detect Magic</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   3</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 200</cost>
	</spell>

	<spell>
	    <name>Disenchant Area</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  50</bcost>
	    <cost>  50</cost>
	</spell>

	<spell>
	    <name>Disjunction</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 200</cost>
	</spell>

	<spell>
	    <name>Dispel Magic</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  10</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Enchant Item</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost>   0</cost>
	</spell>

	<spell>
	    <name>Magic Spirit</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   1</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost>  30</cost>
	</spell>

	<spell>
	    <name>Spell Of Mastery</name>
	    <rank>special</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost>5000</cost>
	</spell>

	<spell>
	    <name>Spell Of Return</name>
	    <rank>special</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost>1000</cost>
	</spell>

	<spell>
	    <name>Summon Champion</name>
	    <rank>uncommon</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 750</cost>
	</spell>

	<spell>
	    <name>Summon Hero</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost> 300</cost>
	</spell>

	<spell>
	    <name>Summoning Circle</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>   0</bcost>
	    <cost>  50</cost>
	</spell>

	<spell>
	    <name>Recall Hero</name>
	    <rank>common</rank>
	    <type> </type>
	    <info> </info>
	    <gfx> </gfx>
	    <upkeep>   0</upkeep>
	    <know>   0</know>
	    <bcost>  20</bcost>
	    <cost>   0</cost>
	</spell>
</book>
</realm>
